SNMP: SNMP::Type Class Reference
SNMP::Type Class Reference
Type of a BER object.
#include <src/BER.h>
Public Types
enum : uint16_t {
Boolean = Class::Universal | Form::Primitive | 0x01 , Integer , BitString , OctetString ,
Null , ObjectIdentifier , Sequence = Class::Universal | Form::Constructed | 0x10 , IPAddress = Class::Application | 0x00 ,
Counter32 , Gauge32 , TimeTicks , Opaque ,
Counter64 = Class::Application | 0x06 , Float = Class::Application | 0x08 , NoSuchObject = Class::Context | 0x00 , NoSuchInstance ,
EndOfMIBView , GetRequest = Class::Context | Form::Constructed | 0x00 , GetNextRequest , GetResponse ,
SetRequest , Trap , GetBulkRequest , InformRequest ,
SNMPv2Trap , Report , OpaqueFloat = 0x9F78
}
Enumerates most of type values.
Public Member Functions
Type (const unsigned int type=0)
Creates a BER type from a type value.
Type (const uint8_t flag, const unsigned int tag)
Creates a BER type from a composite type value.
void encode (Stream &stream)
Encodes BER type to stream.
void decode (Stream &stream)
Decodes BER type from stream.
uint8_t * encode (uint8_t *buffer)
Encodes BER type to memory buffer.
uint8_t * decode (uint8_t *buffer)
Decodes BER type from memory buffer.
operator unsigned int () const
Unsigned int conversion function.
const uint8_t getClass () const
Gets class from BER type.
const uint8_t getForm () const
Gets form from BER type.
const unsigned int getTag () const
Gets tag from BER type.
Public Member Functions inherited from SNMP::Base
void encode7bits (uint32_t value, uint8_t *buffer, const uint8_t size)
Encodes integer value to memory buffer.
Private Member Functions
void setType (unsigned int type)
Sets BER type from type value.
void setFlagTag (uint8_t flag, unsigned int tag)
Creates a BER type from a composite type value.
Private Attributes
uint8_t _class
uint8_t _form
unsigned int _tag
unsigned int _type
Additional Inherited Members
Static Public Member Functions inherited from SNMP::Base
static void encode7bits (uint32_t value, Stream &stream, const uint8_t size)
Encodes integer value to stream.
Protected Attributes inherited from SNMP::Base
unsigned int _size = 0
Detailed Description
Type of a BER object.
This class handles the type of a BER object.
A type has 3 elements.
Class.
Form.
Tag.
Definition at line 282 of file BER.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint16_t
Enumerates most of type values.
Enumerator
Boolean
0x01
Integer
0x02
BitString
0x03
OctetString
0x04
Null
0x05
ObjectIdentifier
0x06
Sequence
0x30
IPAddress
0x40
Counter32
0x41
Gauge32
0x42
TimeTicks
0x43
Opaque
0x44
Counter64
0x46
Float
0x48
NoSuchObject
0x80
NoSuchInstance
0x81
EndOfMIBView
0x82
GetRequest
0xA0
GetNextRequest
0xA1
GetResponse
0xA2
SetRequest
0xA3
Trap
0xA4
GetBulkRequest
0xA5
InformRequest
0xA6
SNMPv2Trap
0xA7
Report
0xA8
OpaqueFloat
0x9F78
Definition at line 287 of file BER.h.
Constructor & Destructor Documentation
Type() [1/2]
SNMP::Type::Type (const unsigned int type = 0) inline
Creates a BER type from a type value.
Parameters
type BER Type.
Definition at line 329 of file BER.h.
References setType().
Type() [2/2]
SNMP::Type::Type (const uint8_t flag, const unsigned int tag) inline
Creates a BER type from a composite type value.
Type value is computed from flag (class and form) and tag.
Parameters
flag Flag (class and form).
tag Tag.
Definition at line 342 of file BER.h.
References setFlagTag().
Member Function Documentation
decode() [1/2]
void SNMP::Type::decode (Stream & stream) inline
Decodes BER type from stream.
Parameters
stream Stream to read from.
Definition at line 372 of file BER.h.
References _class, _form, SNMP::Base::_size, _tag, and _type.
Referenced by SNMP::ArrayBER< U >::decode(), SNMP::ArrayBER< U >::decode(), SNMP::BER::decode(), SNMP::BER::decode(), SNMP::OpaqueBER::decode(), and SNMP::OpaqueBER::decode().
decode() [2/2]
uint8_t * SNMP::Type::decode (uint8_t * buffer) inline
Decodes BER type from memory buffer.
Parameters
buffer Pointer to the buffer.
Returns
Next position to be read in buffer.
Definition at line 417 of file BER.h.
References _class, _form, _tag, and _type.
encode() [1/2]
void SNMP::Type::encode (Stream & stream) inline
Encodes BER type to stream.
There is two ways to encode a BER type.
Short form if tag < 31.
Long form otherwise.
Parameters
stream Stream to write to.
Definition at line 358 of file BER.h.
References _class, _form, SNMP::Base::_size, _tag, and SNMP::Base::encode7bits().
Referenced by SNMP::BER::encode(), and SNMP::BER::encode().
encode() [2/2]
uint8_t * SNMP::Type::encode (uint8_t * buffer) inline
Encodes BER type to memory buffer.
There is two ways to encode a BER type.
Short form if tag < 31.
Long form otherwise.
Parameters
buffer Pointer to the buffer.
Returns
Next position to be written in buffer.
Definition at line 401 of file BER.h.
References _class, _form, SNMP::Base::_size, _tag, and SNMP::Base::encode7bits().
getClass()
const uint8_t SNMP::Type::getClass () const inline
Gets class from BER type.
Returns
Class from BER type.
Definition at line 451 of file BER.h.
References _class.
getForm()
const uint8_t SNMP::Type::getForm () const inline
Gets form from BER type.
Returns
Form from BER type.
Definition at line 460 of file BER.h.
References _form.
getTag()
const unsigned int SNMP::Type::getTag () const inline
Gets tag from BER type.
Returns
Tag from BER type.
Definition at line 469 of file BER.h.
References _tag.
operator unsigned int()
SNMP::Type::operator unsigned int () const inline
Unsigned int conversion function.
Gets type as integer.
Returns
BER type.
Definition at line 442 of file BER.h.
References _type.
setFlagTag()
void SNMP::Type::setFlagTag (uint8_t flag, unsigned int tag) inline private
Creates a BER type from a composite type value.
type value is computed from flag (class and form) and tag.
Type is set and the size is computed again.
Parameters
flag Flag (class and form).
tag Tag.
Definition at line 521 of file BER.h.
References _class, _form, SNMP::Base::_size, _tag, and _type.
Referenced by Type().
setType()
void SNMP::Type::setType (unsigned int type) inline private
Sets BER type from type value.
Type is set and the size is computed again.
Parameters
type BER type.
Definition at line 490 of file BER.h.
References _class, _form, SNMP::Base::_size, _tag, and _type.
Referenced by Type().
Member Data Documentation
_class
uint8_t SNMP::Type::_class private
Class of the BER type.
Definition at line 475 of file BER.h.
Referenced by decode(), decode(), encode(), encode(), getClass(), setFlagTag(), and setType().
_form
uint8_t SNMP::Type::_form private
Form of the BER type.
Definition at line 477 of file BER.h.
Referenced by decode(), decode(), encode(), encode(), getForm(), setFlagTag(), and setType().
_tag
unsigned int SNMP::Type::_tag private
Tag of the BER type.
Definition at line 479 of file BER.h.
Referenced by decode(), decode(), encode(), encode(), getTag(), setFlagTag(), and setType().
_type
unsigned int SNMP::Type::_type private
Type of the BER object.
Definition at line 481 of file BER.h.
Referenced by decode(), decode(), operator unsigned int(), setFlagTag(), and setType().
The documentation for this class was generated from the following file:
BER.h